version: '3'
services:
  web:
    build:
      context: ./  # Set the context to the current directory (where docker-compose.yml is located)
      dockerfile: ./Dockerfile  # Specify the path to your Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=app.py
      - ELASTICSEARCH_HOST=elasticsearch
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
